/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_NkdJniTest */

#ifndef _Included_my_NkdJniTest
#define _Included_my_NkdJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_NkdJniTest
 * Method:    myTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_NkdJniTest_myTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
